export const shipList: string[] =
    [
        "Amarr Shuttle",
        "Minmatar Shuttle",
        "Gallente Shuttle",
        "Caldari Shuttle",
        "Goru's Shuttle",
        "Guristas Shuttle",
        "Bantam",
        "Condor",
        "Griffin",
        "Kestrel",
        "Merlin",
        "Heron",
        "Slasher",
        "Probe",
        "Rifter",
        "Breacher",
        "Burst",
        "Vigil",
        "Executioner",
        "Inquisitor",
        "Tormentor",
        "Punisher",
        "Crucifier",
        "Magnate",
        "Navitas",
        "Tristan",
        "Incursus",
        "Imicus",
        "Atron",
        "Maulus",
        "Venture",
        "Citizen Venture",
        "Succubus",
        "Cruor",
        "Daredevil",
        "Worm",
        "Dramiel",
        "Astero",
        "Garmur",
        "Caldari Navy Hookbill",
        "Imperial Navy Slicer",
        "Republic Fleet Firetail",
        "Federation Navy Comet",
        "Police Pursuit Comet",
        "Crucifier Navy Issue",
        "Vigil Fleet Issue",
        "Griffin Navy Issue",
        "Maulus Navy Issue",
        "Probe Fleet Issue",
        "Heron Navy Issue",
        "Magnate Navy Issue",
        "Imicus Navy Issue",
        "Skybreaker",
        "Crusader",
        "Malediction",
        "Crow",
        "Raptor",
        "Taranis",
        "Ares",
        "Claw",
        "Stiletto",
        "Anathema",
        "Purifier",
        "Buzzard",
        "Manticore",
        "Helios",
        "Nemesis",
        "Cheetah",
        "Hound",
        "Vengeance",
        "Retribution",
        "Hawk",
        "Harpy",
        "Ishkur",
        "Enyo",
        "Wolf",
        "Jaguar",
        "Nergal",
        "Sentinel",
        "Kitsune",
        "Keres",
        "Hyena",
        "Prospect",
        "Endurance",
        "Deacon",
        "Kirin",
        "Thalia",
        "Scalpel",
        "Damavik",
        "Stabber",
        "Rupture",
        "Bellicose",
        "Scythe",
        "Maller",
        "Augoror",
        "Arbitrator",
        "Omen",
        "Test Site Maller",
        "Osprey",
        "Caracal",
        "Moa",
        "Blackbird",
        "Vexor",
        "Thorax",
        "Celestis",
        "Exequror",
        "Guardian",
        "Basilisk",
        "Oneiros",
        "Scimitar",
        "Zarmazd",
        "Zealot",
        "Sacrilege",
        "Cerberus",
        "Eagle",
        "Ishtar",
        "Deimos",
        "Vagabond",
        "Muninn",
        "Ikitursa",
        "Pilgrim",
        "Curse",
        "Falcon",
        "Rook",
        "Arazu",
        "Lachesis",
        "Huginn",
        "Rapier",
        "Devoter",
        "Onyx",
        "Phobos",
        "Broadsword",
        "Legion",
        "Tengu",
        "Proteus",
        "Loki",
        "Monitor",
        "Caracal Navy Issue",
        "Omen Navy Issue",
        "Stabber Fleet Issue",
        "Vexor Navy Issue",
        "Scythe Fleet Issue",
        "Augoror Navy Issue",
        "Osprey Navy Issue",
        "Exequror Navy Issue",
        "Gila",
        "Phantasm",
        "Cynabal",
        "Vigilant",
        "Ashimmu",
        "Stratios",
        "Orthrus",
        "Stormbringer",
        "Vedmak",
        "Rodiva",
        "Coercer",
        "Dragoon",
        "Cormorant",
        "Corax",
        "Catalyst",
        "Algos",
        "Thrasher",
        "Talwar",
        "Heretic",
        "Flycatcher",
        "Eris",
        "Sabre",
        "Confessor",
        "Svipul",
        "Jackdaw",
        "Hecate",
        "Pontifex",
        "Stork",
        "Magus",
        "Bifrost",
        "Draugur",
        "Kikimora",
        "Coercer Navy Issue",
        "Thrasher Fleet Issue",
        "Cormorant Navy Issue",
        "Catalyst Navy Issue",
        "Mekubal",
        "Mamba",
        "Tholos",
        "Oracle",
        "Prophecy",
        "Harbinger",
        "Naga",
        "Ferox",
        "Drake",
        "Talos",
        "Brutix",
        "Myrmidon",
        "Tornado",
        "Cyclone",
        "Hurricane",
        "Absolution",
        "Damnation",
        "Vulture",
        "Nighthawk",
        "Eos",
        "Astarte",
        "Sleipnir",
        "Claymore",
        "Brutix Navy Issue",
        "Drake Navy Issue",
        "Harbinger Navy Issue",
        "Hurricane Fleet Issue",
        "Cyclone Fleet Issue",
        "Ferox Navy Issue",
        "Myrmidon Navy Issue",
        "Prophecy Navy Issue",
        "Alligator",
        "Khizriel",
        "Cenotaph",
        "Drekavac",
        "Tempest",
        "Typhoon",
        "Maelstrom",
        "Apocalypse",
        "Armageddon",
        "Abaddon",
        "Raven",
        "Scorpion",
        "Rokh",
        "Megathron",
        "Dominix",
        "Hyperion",
        "Redeemer",
        "Widow",
        "Sin",
        "Panther",
        "Paladin",
        "Golem",
        "Kronos",
        "Vargur",
        "Raven Navy Issue",
        "Apocalypse Navy Issue",
        "Megathron Navy Issue",
        "Tempest Fleet Issue",
        "Armageddon Navy Issue",
        "Dominix Navy Issue",
        "Scorpion Navy Issue",
        "Typhoon Fleet Issue",
        "Nightmare",
        "Machariel",
        "Vindicator",
        "Rattlesnake",
        "Bhaalgorn",
        "Nestor",
        "Barghest",
        "Thunderchild",
        "Leshak",
        "Vehement",
        "Chemosh",
        "Caiman",
        "Naglfar Fleet Issue",
        "Revelation Navy Issue",
        "Moros Navy Issue",
        "Phoenix Navy Issue",
        "Zirnitra",
        "Revelation",
        "Phoenix",
        "Moros",
        "Naglfar",
        "Bane",
        "Karura",
        "Valravn",
        "Hubris",
        "Providence",
        "Charon",
        "Obelisk",
        "Fenrir",
        "Bowhead",
        "Avalanche",
        "Avatar",
        "Leviathan",
        "Erebus",
        "Ragnarok",
        "Vanquisher",
        "Molok",
        "Komodo",
        "Azariel",
        "Archon",
        "Aeon",
        "Chimera",
        "Wyvern",
        "Thanatos",
        "Nyx",
        "Vanguard",
        "Hel",
        "Nidhoggur",
        "Revenant",
        "Vendetta",
        "Rorqual",
        "Ark",
        "Rhea",
        "Anshar",
        "Nomad",
        "Apostle",
        "Minokawa",
        "Ninazu",
        "Venerable",
        "Lif",
        "Dagon",
        "Loggerhead",
        "Hoarder",
        "Mammoth",
        "Wreathe",
        "Nereus",
        "Kryos",
        "Epithal",
        "Miasmos",
        "Iteron Mark V",
        "Badger",
        "Tayra",
        "Bestower",
        "Sigil",
        "Noctis",
        "Squall",
        "Prorator",
        "Impel",
        "Crane",
        "Bustard",
        "Viator",
        "Occator",
        "Prowler",
        "Mastodon",
        "Deluge",
        "Torrent",
        "Orca",
        "Porpoise",
        "Covetor",
        "Retriever",
        "Procurer",
        "Hulk",
        "Skiff",
        "Mackinaw",
        "Primae",
        "Miasmos Quafe Ultra Edition",
        "Miasmos Quafe Ultramarine Edition",
        "Miasmos Amastris Edition",
        "Apotheosis",
        "InterBus Shuttle",
        "Leopard",
        "Council Diplomatic Shuttle",
        "Boobook",
        "Zephyr",
        "Echelon",
        "Gold Magnate",
        "Silver Magnate",
        "Metamorphosis",
        "Scorpion Ishukone Watch",
        "Apocalypse Imperial Issue",
        "Armageddon Imperial Issue",
        "Megathron Federate Issue",
        "Raven State Issue",
        "Tempest Tribal Issue",
        "Marshal",
        "Praxis",
        "Python",
        "Adrestia",
        "Vangel",
        "Mimir",
        "Bestla",
        "Cybele",
        "Utu",
        "Malice",
        "Freki",
        "Cambion",
        "Geri",
        "Shapash",
        "Etana",
        "Rabisu",
        "Gnosis",
        "Opux Luxury Yacht",
        "Guardian-Vexor",
        "Victorieux Luxury Yacht",
        "Moracha",
        "Chameleon",
        "Enforcer",
        "Victor",
        "Tiamat",
        "Cobra",
        "Chremoas",
        "Caedes",
        "Pacifier",
        "Virtuoso",
        "Hydra",
        "Sidewinder",
        "Whiptail",
        "Imp",
        "Fiend",
        "Laelaps",
        "Sunesis",
        "Immolator",
        "Echo",
        "Hematos",
        "Taipan",
        "Violator",
        "Raiju",
        "Impairor",
        "Ibis",
        "Velator",
        "Reaper"
    ]
    ;